services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.test
    command: ["pytest", "--disable-warnings"]
    depends_on:
      - db
