"""add comments

Revision ID: 6556ef5ef304
Revises: 7d6d65895a58
Create Date: 2025-07-22 13:32:47.725846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6556ef5ef304'
down_revision: Union[str, None] = '7d6d65895a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(op.f('comments_author_id_fkey'), 'comments', type_='foreignkey')
    op.drop_constraint(op.f('comments_post_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_post_id_fkey'), 'comments', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(op.f('comments_author_id_fkey'), 'comments', 'users', ['author_id'], ['id'])
    op.alter_column('comments', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
